### ISSUE TITLE
ImportError: cannot import name HTTPSConnection

### ISSUE THREAD

**Issue by naholyr** [bgreenlee/sublime-github#6]
Hello,

After installing this plugin from Package Control on a Ubuntu 11.10 system, I get this in the console:

```
Reloading plugin /home/nchambrier/.config/sublime-text-2/Packages/sublime-github/gist.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./gist.py", line 10, in <module>
    import requests
  File "/home/nchambrier/.config/sublime-text-2/Packages/sublime-github/lib/requests/__init__.py", line 26, in <module>
    from . import utils
  File "/home/nchambrier/.config/sublime-text-2/Packages/sublime-github/lib/requests/utils.py", line 19, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/nchambrier/.config/sublime-text-2/Packages/sublime-github/lib/requests/compat.py", line 86, in <module>
    from .packages.oreos.monkeys import SimpleCookie
  File "/home/nchambrier/.config/sublime-text-2/Packages/sublime-github/lib/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/nchambrier/.config/sublime-text-2/Packages/sublime-github/lib/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/home/nchambrier/.config/sublime-text-2/Packages/sublime-github/lib/requests/packages/urllib3/connectionpool.py", line 22, in <module>
    from httplib import HTTPConnection, HTTPSConnection, HTTPException
ImportError: cannot import name HTTPSConnection
```

The thing I don't understand is that I have only one version of Python installed, and when I run python REPL I can see the import working:

```
$ python
Python 2.7.2+ (default, Oct  4 2011, 20:03:08) 
[GCC 4.6.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from httplib import HTTPConnection, HTTPSConnection, HTTPException
>>> HTTPSConnection
<class httplib.HTTPSConnection at 0x8cdee9c>
```

**Comment by ishandutta2007** [comment]
I had a similar problem where the issue was openssl was updated but python was not recompiled, basically whenever you update openssl you have to recompile python.
https://github.com/jarun/googler/issues/312
