### ISSUE TITLE
Doesn't seem to work in Windows

### ISSUE THREAD

**Issue by MarcosBL** [bgreenlee/sublime-github#62]
Installed trought Package control (Windows XP SP3 32 bits):

```
reloading plugin sublime-github.github
reloading plugin sublime-github.sublime_github
Traceback (most recent call last):
  File "C:\Archivos de programa\Sublime Text 3\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "C:\Archivos de programa\Sublime Text 3\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_github in C:\Documents and Settings\Administrador\Datos de programa\Sublime Text 3\Installed Packages\sublime-github.sublime-package", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "C:\Documents and Settings\Administrador\Datos de programa\Sublime Text 3\Installed Packages\sublime-github.sublime-package\lib\git.py", line 129, in <module>
  File "C:\Documents and Settings\Administrador\Datos de programa\Sublime Text 3\Installed Packages\sublime-github.sublime-package\lib\git.py", line 120, in find_git
  File "X/os.py", line 669, in __getitem__
KeyError: 'PROGRAMFILES(X86)'
```

**Comment by markschwarz** [comment]
Hm.  It seemed to work well for me on Win 7, save the behavior in https://github.com/bgreenlee/sublime-github/issues/82.
