### ISSUE TITLE
GitHub commands not found in the Command Palette

### ISSUE THREAD

**Issue by MrJellyB** [bgreenlee/sublime-github#72]
Hey there.
After I installed "sublime-github" from the package control I couldn't
find any of the "sublime-github" commands in the Command Palette.
What can I do?

**Comment by entr** [comment]
```
reloading plugin sublime-github.sublime_github
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "sublime_github in C:\Users\Zlatko\AppData\Roaming\Sublime Text 3\Installed Packages\sublime-github.sublime-package", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Users\Zlatko\AppData\Roaming\Sublime Text 3\Installed Packages\sublime-github.sublime-package\lib\git.py", line 129, in <module>
  File "C:\Users\Zlatko\AppData\Roaming\Sublime Text 3\Installed Packages\sublime-github.sublime-package\lib\git.py", line 120, in find_git
  File "./os.py", line 676, in __getitem__
KeyError: 'ProgramFiles(x86)'
reloading plugin sublime-github.sublime_requests
```
Installing GIT fixed it. LOL

Windows 8.1 x86
